package Runners;

import StoryElements.Book;
import StoryElements.Chapter;
import StoryElements.Node;
import StoryElements.Page;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;
import javax.swing.JButton;

public class PreviewFrame extends javax.swing.JFrame {

    private String mode;
    private MainFrame main;
    private Book book;
    private Chapter chapter;
    private Page page;
    private ArrayList<JButton> buttons;
    private ArrayList<Node> nodes;
    private boolean title;//for when preview first starts
    private boolean chpTitle;//for new chapters
    
    public PreviewFrame(String mode, MainFrame main) {
        System.out.println("initializing preview frame...");
        initComponents();
        setLocationRelativeTo(null);
        this.mode = mode;
        this.main=main;
        book=main.getCurrentBook();
        setTitle(book.getTitle());
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        buttons=new ArrayList();
        buttons.add(button1);
        buttons.add(button2);
        buttons.add(button3);
        buttons.add(button4);
        buttons.add(button5);
        for (JButton b: buttons){
            b.setEnabled(false);
            b.setText("");
        }
        textTitle.setText(book.getTitle());
        button1.setText("Next");
        button1.setEnabled(true);
        title=true;
        chpTitle=false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        textTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        button1.setText("jButton1");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setText("jButton2");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setText("jButton3");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        button4.setText("jButton4");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setText("jButton5");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textTitle)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(buttonExit)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonExit)
                .addGap(78, 78, 78)
                .addComponent(button1)
                .addGap(87, 87, 87)
                .addComponent(button2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button3)
                .addGap(82, 82, 82)
                .addComponent(button4)
                .addGap(90, 90, 90)
                .addComponent(button5)
                .addGap(46, 46, 46))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if (title){
            startup();
            title=false;
        }
        else if(chpTitle){
            nextPage();
            chpTitle=false;
        }
        else{
            Node n=nodes.get(0);
            Chapter c = chapter;//for determining whether reader has entered a new chapter
            chapter=n.getLinkedChapter();
            page=n.getLinkedPage();
            for (JButton b: buttons)
                b.setEnabled(false);
            if (c!=chapter)
                nextChapter();
            else
                nextPage();
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Node n=nodes.get(1);
        Chapter c = chapter;//for determining whether reader has entered a new chapter
        chapter=n.getLinkedChapter();
        page=n.getLinkedPage();
        for (JButton b: buttons)
            b.setEnabled(false);
        if (c!=chapter)
            nextChapter();
        else
            nextPage();
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        Node n=nodes.get(2);
        Chapter c = chapter;//for determining whether reader has entered a new chapter
        chapter=n.getLinkedChapter();
        page=n.getLinkedPage();
        for (JButton b: buttons)
            b.setEnabled(false);
        if (c!=chapter)
            nextChapter();
        else
            nextPage();
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        Node n=nodes.get(3);
        Chapter c = chapter;//for determining whether reader has entered a new chapter
        chapter=n.getLinkedChapter();
        page=n.getLinkedPage();
        for (JButton b: buttons)
            b.setEnabled(false);
        if (c!=chapter)
            nextChapter();
        else
            nextPage();
    }//GEN-LAST:event_button4ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        Node n=nodes.get(4);
        Chapter c = chapter;//for determining whether reader has entered a new chapter
        chapter=n.getLinkedChapter();
        page=n.getLinkedPage();
        for (JButton b: buttons)
            b.setEnabled(false);
        if (c!=chapter)
            nextChapter();
        else
            nextPage();
    }//GEN-LAST:event_button5ActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonExitActionPerformed
    
    private void startup(){//initializes preview frame using preferred setting
        System.out.println("starting preview...");
        if (mode.equals("beginning")){
            startBeginning();
        }
        else if (mode.equals("chapter")){
            startChapter();
        }
        else if (mode.equals("page")){
            startPage();
        }
    }
    
    private void startBeginning(){
        chapter=book.getChapters().get(0);
        page=chapter.getPages().get(0);
        nextChapter();
    }
    
    private void startChapter(){
        chapter=main.getCurrentChapter();
        page=chapter.getPages().get(0);
        nextChapter();
    }
    
    private void startPage(){
        chapter=main.getCurrentChapter();
        page=main.getCurrentPage();
        textTitle.setText(page.getTitle());
        textArea.setText(page.getStory());
        showNodes();
    }
    
    private void showNodes(){
        nodes=page.getNodes();
        for (int k=0; k<nodes.size(); k++){
            JButton b = buttons.get(k);
            Node n = nodes.get(k);
            b.setText(n.getTitle());
            b.setEnabled(true);
        }
    }
    
    private void clearNodes(){
        for (JButton b: buttons){
            b.setEnabled(false);
            b.setText("-");
        }
    }
    
    private void nextPage(){
        clearNodes();
        textTitle.setText(page.getTitle());
        textArea.setText(page.getStory());
        showNodes();
    }
    
    private void nextChapter(){
        clearNodes();
        textArea.setText("");
        textTitle.setText(chapter.getTitle());
        chpTitle=true;
        button1.setEnabled(true);
        button1.setText("Next");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton buttonExit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textTitle;
    // End of variables declaration//GEN-END:variables
}
